### ISSUE TITLE
Mangaworld IT

### ISSUE THREAD

**Issue by Peppepsp** [PhantomShift/nekotatsu#2]
Mangaworld IT won't convert, it miss all when i try to convert from tachiyomi to kotatsu

**Comment by PhantomShift** [comment]
I'm assuming [this](https://github.com/KotatsuApp/kotatsu-parsers/issues/438) is the source you're talking about? As far as I can tell they haven't added it to Kotatsu, so there's no corresponding parser to convert to for Kotatsu.

Feel free to open this again if they add it and it still fails to convert after updating (`nekotatsu update --force-download`).
