### ISSUE TITLE
[Failing Conversion]: All sources fail and process ends early

### ISSUE THREAD

**Issue by WARlord05** [PhantomShift/nekotatsu#5]
### Preface

- [X] I have checked that the source is implemented in the [Kotatsu parsers repo](https://github.com/KotatsuApp/kotatsu-parsers)
- [X] I have tried force updating the sources (`nekotatsu update --force-download`)
- [x] (OPTIONAL) The source is listed by [Keiyoushi](https://keiyoushi.github.io/extensions/)

### Source Name

all sources conversion failed ,the process did not even start

### Additional Context

Error: Custom { kind: NotFound, error: "Source not found" }

**Comment by WARlord05** [comment]
this is the command used === ./nekotatsu convert -v eu.kanade.tachiyomi.j2k_2024-06-28_15-34.tachibk
few examples


[WARNING] Unable to convert Absolute Sword Sense from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert Arcana Fantasy from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert Archmage Transcending Through Regression from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert Attouteki Gacha Un De Isekai O Nariagaru! from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert Boundless Necromancer from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert Cheat Kusushi no Slow Life: Isekai ni Tsukurou Drugstore from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert Circle Zero's Otherworldly Hero Business from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert Damn Reincarnation from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert Hajimete no Gal from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert Heavenly Sword’s Grand Saga from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert I Am the Fated Villain from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert I Awakened to the Ex Skill  from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert I Have a Slow Living in Different World (I Wish) from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert I Obtained a Mythic Item from source Mangahere (https://www.mangahere.cc)
[WARNING] Unable to convert I Reincarnated As The Crazed Heir from source Asura Scans (https://asuracomic.net)
[WARNING] Unable to convert Insanely-Talented Player from source Asura Scans (https://asuracomic.net)


and then

Error: Custom { kind: NotFound, error: "Source not found" }

**Comment by PhantomShift** [comment]
Interesting, wonder if it's because it's a j2k backup, I've only tested on Neko and vanilla Tachiyomi backups since they're the only ones I've used. Thanks for the report.

**Comment by PhantomShift** [comment]
I'm still not sure what's up with the Asura Scans ones failing but a parser for MangaHere hasn't been implemented yet.
https://github.com/KotatsuApp/kotatsu-parsers/issues/570
Do you mind sending your backup file? It'd be very helpful, but I'll continue investigating regardless.
Also, do you happen to know how you added the Asura Scans extension and when? (i.e. from Keiyoushi or a different repository) I quickly tested with a fresh installation using Keiyoushi and it converted just fine which is confusing me at the moment.

**Comment by WARlord05** [comment]
The error is provided in the file.
[Error log.txt](https://github.com/user-attachments/files/16033526/Error.log.txt)

This is the backups used.
[Tachibk files.zip](https://github.com/user-attachments/files/16033542/Tachibk.files.zip)
There is also one backup from tachiyomiS97 and two from j2k.
Also try this backup,
[eu.kanade.tachiyomi.j2k_2024-06-28_22-14.zip](https://github.com/user-attachments/files/16033709/eu.kanade.tachiyomi.j2k_2024-06-28_22-14.zip)


Regarding the Asura Scans(install apk type) i have been using it since when the original tachiyomi stopped supporting the extension in its browse. Not just asura even all the other sources in error file also.

This is the Repo for extentions:- https://raw.githubusercontent.com/ThePBone/tachiyomi-extensions-revived/repo/index.min.json

Note:- There are many sources used by comics in my library. There are not from only 2 or 3 source its like 6 or 7 sources

**Comment by WARlord05** [comment]
update:- it kinda worked on vanilla tachibk but still,
This is what i got,
[Vani Error log.txt](https://github.com/user-attachments/files/16034022/Vani.Error.log.txt)
MangaHere Error is understandable but the other one kinda over my head

Repo used this time was:- https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

This is the vanilla tachiyomi bak used.
[eu.kanade.tachiyomi_2024-06-28_22-27.zip](https://github.com/user-attachments/files/16034050/eu.kanade.tachiyomi_2024-06-28_22-27.zip)

And this is the output,
[neko_converted.zip](https://github.com/user-attachments/files/16034079/neko_converted.zip)

When transferred, the chapters in some manga didn't match of how many were read, though that is understandable as not everything is perfect. Some manga where also missing even though they don't show in the error or are from either of the 2 failed sources in the error file.

Hope this help for the improvement of the project as it is a huge plus for me who tests out different readers and as my main library is on tachiyomi based readers which limited me those only.

**Comment by PhantomShift** [comment]
> This is the Repo for extentions:- https://raw.githubusercontent.com/ThePBone/tachiyomi-extensions-revived/repo/index.min.json

Ah I believe this is the main culprit for failed conversions. You can tell nekotatsu to use this link instead of keiyoushi by running this command
```bash
nekotatsu update -t https://raw.githubusercontent.com/ThePBone/tachiyomi-extensions-revived/repo/index.min.json
```
Meanwhile the error at the end is because I didn't consider the case where the source is a locally saved manga that the user added manually.

Currently testing with the backups you gave me and it seems that most of the errors are due to not being present in Kotatsu but some are still failing despite being implemented so I need to do a bit more investigation.

**Comment by PhantomShift** [comment]
> Currently testing with the backups you gave me and it seems that most of the errors are due to not being present in Kotatsu but some are still failing despite being implemented so I need to do a bit more investigation.

Disregard this last bit, this was due to not updating my parser list. The rest do not seem to be implemented in Kotatsu (some *names* fit but their URLs don't).

**Comment by PhantomShift** [comment]
Everything should be settled with this [new release](https://github.com/PhantomShift/nekotatsu/releases/tag/v1.1.3) but if there's some issue persisting please feel free to re-open, otherwise file another issue. Just to reiterate, you need to make sure to override the extension source with `nekotatsu update -t https://raw.githubusercontent.com/ThePBone/tachiyomi-extensions-revived/repo/index.min.json` since your J2K backup used that extension list. Thank you for the report and cooperation!
