### ISSUE TITLE
[improvements]Request to add source parser

### ISSUE THREAD

**Issue by WARlord05** [PhantomShift/nekotatsu#6]
Mangahere (https://www.mangahere.cc)
IsekaiScanManga (unoriginal) (https://isekaiscanmanga.com)
Asura Scans (https://asuracomic.net)
IsekaiScan.to (unoriginal) (https://m.isekaiscan.to)

**Comment by PhantomShift** [comment]
Did you mean to send this to https://github.com/KotatsuApp/kotatsu-parsers? There's nothing I can do on my side for these.
Mangahere's open request https://github.com/KotatsuApp/kotatsu-parsers/issues/570
