### ISSUE TITLE
Neko favourites are not detected

### ISSUE THREAD

**Issue by ItachiSan** [PhantomShift/nekotatsu#7]
I am unable to generate favourites via a Neko backup.

## Process
1. Create a Neko backup
2. Convert via Nekotatsu
3. Import in Kotatsu

## Expected
I can import history and library (favourites)

## What happens
I only have my history, not my favorites.

## Additional notes
Mihon backups do include the library, although it does not seem to appear in favorites.

## Versions
Latest versions of Neko, Mihon, Kotatsu and Nekotatsu.

**Comment by PhantomShift** [comment]
Ahh, thank you for pointing this out. When using Kotatsu I mainly used the history tab rather than browsing through my favorites, so when I'd written the code initially, I defaulted to putting all the backups into the history as opposed to putting it in favorites. Thank you for the report.

**Comment by PhantomShift** [comment]
Fixed in https://github.com/PhantomShift/nekotatsu/commit/5ee2d53bf9425ec4c5ad8dfcb706eafb6c8b1c57
